%% Step F2+F3: ARMA simulation + inverse SEM verification
%  Uses Python's fitted ARMA coefficients + same eta noise
%  to verify that MATLAB and Python produce identical simulated noise.

clear; close all;

ml_dir = 'D:\Dataset\DPastCliM-NA\verification\step_F\matlab';
py_dir = 'D:\Dataset\DPastCliM-NA\verification\step_F\python';

%% Load Python's ARMA coefficients
fid = fopen(fullfile(py_dir, 'arma_coeffs.bin'), 'r');
n_st = fread(fid, 1, 'int32');
ar_coeffs = fread(fid, n_st, 'double');
ma_coeffs = fread(fid, n_st, 'double');
variances = fread(fid, n_st, 'double');
valid_mask = fread(fid, n_st, 'int32');
fclose(fid);

%% Load shared eta noise (generated by Python with seed=12345)
fid = fopen(fullfile(py_dir, 'eta_noise.bin'), 'r');
hdr = fread(fid, 2, 'int32');
n_st2 = hdr(1); n_sim = hdr(2);
eta_all = fread(fid, [n_sim, n_st2], 'double')';
fclose(fid);

fprintf('Loaded: %d stations, %d sim timesteps\n', n_st, n_sim);
fprintf('Valid stations: %d\n', sum(valid_mask));

%% F2: ARMA simulation (same logic as compute_eps_arma.m)
p = 1; q = 1;
eps_arma_ml = zeros(n_st, n_sim);

for i = 1:n_st
    if ~valid_mask(i), continue; end
    phi = ar_coeffs(i);
    theta = ma_coeffs(i);
    eta = eta_all(i, :);
    eps_tmp = zeros(1, n_sim);
    
    for t = 1:n_sim
        ar_term = 0;
        ma_term = 0;
        for j = 1:p
            if t-j > 0
                ar_term = ar_term + phi * eps_tmp(t-j);
            end
        end
        for j = 1:q
            if t-j > 0
                ma_term = ma_term + theta * eta(t-j);
            end
        end
        eps_tmp(t) = ar_term + ma_term + eta(t);
    end
    eps_arma_ml(i, :) = eps_tmp;
end

%% Load Python's eps_arma and compare
fid = fopen(fullfile(py_dir, 'eps_arma.bin'), 'r');
hdr2 = fread(fid, 2, 'int32');
eps_arma_py = fread(fid, [hdr2(2), hdr2(1)], 'double')';
fclose(fid);

diff_arma = abs(eps_arma_ml - eps_arma_py);
valid_diff = diff_arma(logical(valid_mask), :);
fprintf('\n=== ARMA Simulation Comparison ===\n');
fprintf('Max |diff|: %.6e\n', max(valid_diff(:)));
fprintf('Mean |diff|: %.6e\n', mean(valid_diff(:)));

%% F3: Inverse SEM
% Rebuild W (same as in verify_F_sem.m)
fid = fopen(fullfile(ml_dir, 'coords_sub.bin'), 'r');
raw_coords = fread(fid, [n_st, 2], 'double');
fclose(fid);
x_proj = raw_coords(:,1);
y_proj = raw_coords(:,2);

fid = fopen(fullfile(ml_dir, 'sem_params.bin'), 'r');
lambda_hat = fread(fid, 1, 'double');
threshold_best = fread(fid, 1, 'double');
fclose(fid);

D = sqrt((x_proj - x_proj').^2 + (y_proj - y_proj').^2);
h = threshold_best;
W = exp(-(D.^2)/(2*h^2));
W(eye(n_st)==1) = 0;
rs = sum(W,2); rs(rs==0)=1; W = W ./ rs;
ev = eig(W); rho = max(abs(ev));
if rho >= 1, W = W/(rho+1e-2); end

% inverse SEM: u = (I - lambda*W)^{-1} * eps_arma
A = eye(n_st) - lambda_hat * W;
u_mat_ml = A \ eps_arma_ml;

% Load Python's u_mat
fid = fopen(fullfile(py_dir, 'u_mat.bin'), 'r');
hdr3 = fread(fid, 2, 'int32');
u_mat_py = fread(fid, [hdr3(2), hdr3(1)], 'double')';
fclose(fid);

diff_u = abs(u_mat_ml - u_mat_py);
valid_diff_u = diff_u(logical(valid_mask), :);
fprintf('\n=== Inverse SEM Comparison ===\n');
fprintf('Max |diff|: %.6e\n', max(valid_diff_u(:)));
fprintf('Mean |diff|: %.6e\n', mean(valid_diff_u(:)));

% Save MATLAB outputs
fid = fopen(fullfile(ml_dir, 'eps_arma_ml.bin'), 'w');
fwrite(fid, [n_st, n_sim], 'int32');
fwrite(fid, eps_arma_ml', 'double');
fclose(fid);

fid = fopen(fullfile(ml_dir, 'u_mat_ml.bin'), 'w');
fwrite(fid, [n_st, n_sim], 'int32');
fwrite(fid, u_mat_ml', 'double');
fclose(fid);

fprintf('\nOutputs saved to: %s\n', ml_dir);
